# Generated by Django 5.1.3 on 2024-11-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0003_usuariomodel_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='tipoUsuario',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], db_column='tipo_usuario', default='USER', max_length=100),
        ),
    ]
