# Generated by Django 5.1.3 on 2024-11-17 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0004_alter_usuariomodel_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteosmodel',
            name='posteo',
            field=models.ForeignKey(db_column='posteo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
