# Generated by Django 5.1.3 on 2024-11-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0007_alter_posteosmodel_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteosmodel',
            old_name='posteo',
            new_name='user',
        ),
    ]
